<?php
// This is the ACF version control file
// Every time I change something to the acf, I paste here the code I get from the "php export" feature.

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_homepage-hero-section',
		'title' => 'Homepage Hero Section',
		'fields' => array (
			array (
				'key' => 'field_5935675bab3f4',
				'label' => 'Image background',
				'name' => 'img_background',
				'type' => 'image',
				'instructions' => 'Select the background image for the hero section.<br>
	The image should be at least 1490 × 590.<br>
	Please do not use png but jpg of jpeg files as they are much lighter.',
				'save_format' => 'url',
				'preview_size' => 'large',
				'library' => 'all',
			),
			array (
				'key' => 'field_59356d4fbed21',
				'label' => 'Hero section title',
				'name' => 'hero_title',
				'type' => 'text',
				'instructions' => 'Add the title of the hero section.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59356da0bed22',
				'label' => 'Copy under the title',
				'name' => 'hero_copy',
				'type' => 'textarea',
				'instructions' => 'Add the copy to be shown under the title.',
				'default_value' => 'The Holly Lodge Community Centre offers a whole range of activities in a friendly,
	relaxed environment. We also offer space to hire for events.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59356f56bed27',
				'label' => 'Left Button',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59356dd0bed23',
				'label' => 'Left button text',
				'name' => 'left_btn_text',
				'type' => 'text',
				'instructions' => 'Text to be displayed inside the left button.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59356eb1bed25',
				'label' => 'Left button url',
				'name' => 'left_btn_url',
				'type' => 'page_link',
				'instructions' => 'Select the page you want the button to lead to.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_59356f6bbed28',
				'label' => 'Right Button',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59356e05bed24',
				'label' => 'Right button text',
				'name' => 'right_btn_text',
				'type' => 'text',
				'instructions' => 'Text to be displayed inside the right button.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59356f14bed26',
				'label' => 'Right button url',
				'name' => 'right_btn_url',
				'type' => 'text',
				'instructions' => 'Add the full url of the page you want the button to lead to.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '5',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
